Repository STForScratch/ScratchTools, pull requests merged in 2022-08, with the labels that each got.

#126 Update website domain name and add easter eggs
  README.md
  extras/background.js
  extras/popup.html
  extras/popup.js
  extras/stsettings.css
  features/features.json
  features/follows-you.js
  features/nfe-project-checker.js
  features/rickroll.js
Labels: enhancement, feature, approved, scratch feature, scratchtools feature

#127 Sprite Clone Counter
  features/features.json
  features/sprite-clones.js
Labels: feature, approved, scratch feature

#128 Scrollable list items
  features/features.json
  features/scrollable-list-items.js
Labels: feature, approved, scratch feature

#130 Admin notifications red
  features/admin-notifications.js
  features/features.json
Labels: feature, approved, scratch feature

#131 Block log
  features/block-log.js
  features/features.json
Labels: feature, approved, scratch feature

#134 Update forum-homepage-emojis.js
  features/forum-homepage-emojis.js
Labels: enhancement, feature, approved, scratch feature

#135 Add italic to "empty" text in block log
  features/block-log.js
Labels: enhancement, approved, scratch feature

#136 Fix block log bugs and add fps counter
  features/block-log.js
  features/features.json
  features/fps.js
Labels: bug, feature, approved, scratch feature

#137 Remove blinking features list when searching
  extras/popup.js
Labels: bug, enhancement, feature, approved, scratchtools feature

#138 Add dark mode to ScratchTools settings and add purple icons to beta
  extras/background.js
  extras/dark.png
  extras/day.png
  extras/index.html
  extras/light.png
  extras/lightmode.css
  extras/night.png
  extras/popup.js
  extras/purple-128.png
  extras/purple-16.png
  extras/purple-48.png
  extras/purple.png
  extras/stsettings.css
Labels: enhancement, feature, approved, scratchtools feature

#139 Update version info, change order of features, make popup work in dark mode, and update project timer to fix bug
  extras/new.js
  features/features.json
  features/project-timer.js
  manifest.json
Labels: bug, enhancement, feature, approved, scratch feature, scratchtools feature

#140 Update modal color to not break with website dark modes and add cookies and blockly context menu APIs
  api/cookies.js
  api/vm.js
  extras/background.js
  extras/new.js
  features/collapse-blocks.js
Labels: bug, enhancement, feature, scratch feature, scratchtools feature

#141 Update context menu API name
  api/vm.js
  features/collapse-blocks.js
Labels: enhancement

#142 Fix key codes for block log
  features/block-log.js
Labels: bug, feature, scratch feature

#143 Delete custom block uses
  features/delete-custom-block-uses.js
  features/features.json
Labels: feature, approved, scratch feature

#144 Fix Scratchformat reply box covering up remixes
  features/scratchformat.js
Labels: bug, feature, approved, scratch feature

#145 Stop duplicating hide stickies button
  features/hide-stickies.js
Labels: bug, feature, approved, scratch feature

#146 Stop duplicating check if trending text
  features/check-if-trending.js
Labels: bug, feature, approved, scratch feature

#147 New version update notification
  extras/new.js
Labels: enhancement, feature, approved, scratchtools feature

#148 Add storage API, fix cookies API, add 2.0 Editor Theme, and add Comment on Closed Profile
  api/cookies.js
  api/main.js
  features/comment-on-closed-profile.js
  features/editor-in-two.js
  features/features.json
Labels: bug, enhancement, feature, approved, scratch feature, scratchtools feature

#149 Add Turbowarp Button to Editor
  features/features.json
  features/turbowarp-button-in-editor.js
Labels: feature, approved, scratch feature

#150 Warn when mentioning ScratchTools in a comment
  api/getScratch.js
  api/main.js
  extras/background.js
  extras/new.js
  extras/protect-mention.js
Labels: enhancement, feature, approved, scratchtools feature

#151 Add options to features
  extras/popup.js
  features/features.json
Labels: enhancement, feature, scratchtools feature

#152 Allow features to view options from main world
  extras/background.js
Labels: enhancement, feature, approved, scratchtools feature

#153 Clicker game in popup
  extras/popup.js
Labels: feature, approved, scratchtools feature

#154 Hide advertisements in comments, update logging, and let modals show with dark mode enabled
  api/logging.js
  api/main.js
  extras/new.js
  features/features.json
  features/hide-advertisements.js
Labels: bug, enhancement, feature, approved, scratch feature, scratchtools feature

#155 Fix bugs and remove recommended tag from feature
  extras/index.html
  features/editor-in-two.js
  features/features.json
  features/message-count.js
Labels: bug, enhancement, feature, approved, scratch feature, scratchtools feature

#157 Wait for elements API
  api/main.js
Labels: enhancement, approved

#156 Terrible feature
  features/features.json
  features/terrible.js
Labels: feature, scratch feature

#158 Fix images reloading
  features/terrible.js
Labels: bug, feature, approved, scratch feature

#159 Features API
  api/main.js
  extras/background.js
Labels: enhancement, feature, approved, scratchtools feature

#160 Fix FPS update time
  features/fps.js
Labels: bug, feature, approved, scratch feature

#161 Update version and version info to v2.14.0
  extras/background.js
  extras/new.js
  features/features.json
  manifest.json
Labels: approved

#162 More editor fonts
  api/vm.js
  features/features.json
  features/special-editor-fonts.js
Labels: enhancement, feature, scratch feature, scratchtools feature

#163 Cloud Scratchers feature
  features/cloud-scratchers.js
  features/features.json
Labels: feature, approved, scratch feature

#164 Add more fonts
  features/special-editor-fonts.js
Labels: enhancement, feature, approved, scratch feature

#165 Fix fonts
  features/special-editor-fonts.js
Labels: bug, feature, approved, scratch feature

#166 Set opacity in costume editor
  features/features.json
  features/opacity-setter.js
Labels: feature, approved, scratch feature

#167 Fix opacity setter and move cloud scratchers box to project page
  features/cloud-scratchers.js
  features/opacity-setter.js
Labels: bug, enhancement, feature, approved, scratch feature

#170 Add sound and scratch gui APIs
  api/vm.js
Labels: enhancement, approved

#171 Upgrade background logging, fix wait for element API, and add "Add Last Option List"
  api/main.js
  extras/background.js
  features/add-last-option-list.js
  features/features.json
Labels: bug, enhancement, feature, approved, scratch feature, scratchtools feature

#172 Get project tags
  features/features.json
  features/get-project-tags.js
Labels: feature, approved, scratch feature

#173 Fix custom fonts
  features/custom-fonts.js
Labels: bug, feature, approved

#174 Link Featured Projects to Studio
  features/features.json
  features/link-to-propose.js
Labels: feature, approved, priority #3, scratch website

#176 Fix project tags to only show when tags are used
  features/get-project-tags.js
Labels: feature, approved, priority #2, scratch website, bug fix

#177 Final changes and update version number
  features/features.json
  features/link-to-propose.js
  features/special-editor-fonts.js
  manifest.json
Labels: enhancement, feature, approved, priority #1, scratch website, bug fix
