Repository STForScratch/ScratchTools, pull requests merged in 2022-10, with the labels that each got.

#198 Edited readme
  README.md
Labels: enhancement, approved, priority #3

#200 More efficient full title feature
  features/full-title.js
Labels: enhancement, feature, approved, priority #2, scratch website

#204 Add more dynamic features and fix API
  api/main.js
  features/default-to-local.js
  features/features.json
  features/hide-studio-borders.js
  features/hide-studio-messages.js
  features/infinite-backpack-scrolling.js
Labels: enhancement, feature, priority #1, scratch website, bug fix

#205 Added editor API's to README
  README.md
Labels: enhancement, priority #3, Hacktoberfest, HACKTOBERFEST-ACCEPTED

#203 Safari extension
  README.md
  makefile
Labels: enhancement, HACKTOBERFEST-ACCEPTED

#220 Brand new settings page
  extras/background.js
  extras/blocked.js
  extras/index.html
  extras/mini-logo.svg
  extras/popup.html
  extras/popup.js
  extras/search.svg
  extras/search2.svg
  extras/settings.svg
  features/features.json
Labels: enhancement, scratchtools feature, priority #1, settings page

#222 Dumpster Fire
  features/dumpster-fire.js
  features/features.json
Labels: feature, priority #3, scratch website

#223 Fix default feature functionality, make changes to settings page and news
  extras/background.js
  extras/index.html
  extras/popup.html
  extras/popup.js
Labels: enhancement, feature, scratchtools feature, priority #1, settings page, bug fix

#224 Pause audio
  features/features.json
  features/pause-audio.js
Labels: enhancement, feature, priority #2, scratch website

#226 Fix version bug and add message count in icon
  extras/background.js
  extras/popup.js
  features/features.json
  manifest.json
Labels: enhancement, feature, scratchtools feature, priority #1, bug fix

#227 Fix issue with injection for message count in extension icon
  features/display-message-count-in-icon.js
Labels: priority #1, bug fix

#229 3 new features and remote disable
  api/main.js
  extras/background.js
  extras/index.html
  extras/popup.html
  extras/popup.js
  features/colored-context-menus.js
  features/features.json
  features/follower-count.js
  features/hide-disabled-menu-options.js
  features/left-side-stage.js
  features/move-project-title-input.js
Labels: enhancement, feature, scratchtools feature, priority #1, settings page, scratch website, popup

#230 Reorder new features
  features/features.json
Labels: priority #1

#231 Bump version
  extras/background.js
  extras/new.js
  manifest.json
Labels: priority #2

#232 Bump version with fix to features hiding below when screen isn't wide
  extras/index.html
  manifest.json
Labels: priority #1, settings page, bug fix

#233 Bump version and fix not working for other languages
  features/pause-audio.js
  manifest.json
Labels: priority #1, bug fix

#234 Fix pause audio
  features/pause-audio.js
Labels: priority #1, bug fix
