Repository STForScratch/ScratchTools, pull requests merged in 2022-05, with the labels that each got.

#24 Update stsettings.js
  extras/stsettings.js
Labels: enhancement, approved

#22 Add unbolded text across all of Scratch
  extras/stsettings.js
  features/unbold-forum-topics.js
Labels: feature, approved

#25 Contributor Leaderboard
  extras/leaderboard.html
  extras/popup.html
  extras/popup.js
Labels: feature, scratchtools feature

#26 Update leaderboard.html
  extras/leaderboard.html
Labels: enhancement, approved

#30 Remove The Forbidden Secret (Temporarily)
  extras/stsettings.js
  features.json
  features/the-forbidden-secret.js
  manifest.json
Labels: approved

#31 Compact Navbar
  extras/stsettings.js
  features.json
  features/compact-navbar.js
  manifest.json
Labels: feature, approved, scratch feature

#36 rename myself
  contributors.md
Labels: approved

#39 Start Project on Load
  extras/stsettings.js
  features.json
  features/start-project-on-load.js
  manifest.json
Labels: feature, approved, scratch feature

#41 Recently Viewed Projects
  extras/stsettings.js
  features.json
  features/recently-viewed-projects.js
  manifest.json
Labels: feature, scratch feature

#44 Settings in Extension
  extras/background.js
  extras/popup.html
  extras/popup.js
  extras/stsettings.js
  features.json
  features/advanced-search.js
  features/color-slider-input.js
  features/compact-navbar.js
  features/features.json
  features/full-title.js
  features/message-count.js
  features/more-tutorials.js
  features/nfe-project-checker.js
  features/nfe-search.js
  features/open-in-new-tab.js
  features/plain-background.js
  features/project-links.js
  features/recently-viewed-projects.js
  features/remove-editor-icons.js
  features/round-profile-pictures.js
  features/sidebar.js
  features/sprite-hover-data.js
  features/sprite-watermark.js
  features/start-project-on-load.js
  features/statistics.js
  features/turbowarp-button.js
  features/unbold-forum-topics.js
  features/user-bio.js
  manifest.json
Labels: enhancement, feature, approved, scratchtools feature

#46 Compact Editor (feature), Right Side Flag (feature), and Credits (enhancement)
  extras/popup.js
  features/compact-editor.js
  features/features.json
  features/right-side-flag.js
Labels: enhancement, feature, scratch feature, scratchtools feature

#48 2 New Features and an Enhancement
  extras/background.js
  extras/popup.js
  features/features.json
  features/fixed-box.js
  features/follows-you.js
Labels: enhancement, feature, scratch feature, scratchtools feature

#49 APRIL FOOLS DAY 2022
  features/april-fools.js
  features/features.json
Labels: feature, approved, scratch feature
