Repository STForScratch/ScratchTools, pull requests merged in 2022-07, with the labels that each got.

#69 Clone Counter and Colored Messages
  features/clone-counter.js
  features/colored-messages.js
  features/features.json
Labels: feature, approved, scratch feature

#70 Idea generator
  features/features.json
  features/idea-generator.js
Labels: feature, approved, scratch feature

#71 Aviate Statuses
  features/aviate.js
  features/features.json
Labels: feature, approved, scratch feature

#72 Search Bar
  extras/popup.html
  extras/popup.js
  extras/stsettings.css
Labels: feature, approved, scratchtools feature

#73 Hide scratch news
  features/features.json
  features/hide-scratch-news.js
Labels: feature, scratch feature

#78 Delete all sprites
  features/delete-all.js
  features/features.json
Labels: feature, approved, scratch feature

#79 Sprite data in tabs
  features/features.json
  features/sprite-data.js
Labels: feature, approved, scratch feature

#80 Hide stickies
  features/features.json
  features/hide-stickies.js
Labels: feature, approved, scratch feature

#81 Hide studio group icons
  features/features.json
  features/hide-studio-group-icon.js
Labels: feature, approved, scratch feature

#84 New settings
  extras/index.html
  extras/popup.html
  extras/popup.js
  extras/stsettings.css
  features/features.json
Labels: enhancement

#85 Block users
  extras/background.js
  extras/blocked.js
  extras/index.html
  features/block-messages.js
  features/features.json
Labels: feature, approved, scratch feature

#86 Colored comments
  features/colored-comments.js
  features/features.json
Labels: feature, approved, scratch feature

#87 2.0 block colors and editor dark mode
  features/editor-dark-mode.js
  features/features.json
  features/two-colors.js
Labels: feature, approved, scratch feature

#91 Add settings page filters
  extras/index.html
  extras/popup.js
  features/features.json
Labels: enhancement, approved, scratchtools feature

#92 Most popular project
  features/features.json
  features/most-popular-project.js
Labels: feature, approved, scratch feature

#93 Go to parent
  features/features.json
  features/go-to-parent.js
Labels: feature, approved, scratch feature

#94 Project timer
  features/features.json
  features/project-timer.js
Labels: feature, approved, scratch feature

#97 Scratchformat
  features/features.json
  features/scratchformat.js
Labels: feature, approved, scratch feature

#100 Set featured project
  features/features.json
  features/set-featured-project.js
Labels: feature, approved, scratch feature

#101 Last key pressed
  features/features.json
  features/last-key-pressed.js
Labels: feature, approved, scratch feature

#104 Pin projects
  features/features.json
  features/pin-projects.js
Labels: feature, approved, scratch feature

#105 Better Forum Emojis
  features/features.json
  features/twemoji-in-forums.js
Labels: feature, approved, scratch feature

#106 Hide forum signatures
  features/features.json
  features/hide-signatures.js
Labels: feature, approved, scratch feature

#111 Hide collapse buttons
  features/features.json
  features/remove-collapse-buttons.js
Labels: feature, approved, scratch feature

#112 Forum homepage emojis
  features/features.json
  features/forum-homepage-emojis.js
Labels: feature, approved, scratch feature

#115 Remove topic and post boxes on the forum homepage
  features/features.json
  features/remove-topic-and-post.js
Labels: feature, approved, scratch feature

#116 Click Forum Activity Users
  features/features.json
  features/link-forum-activity.js
Labels: feature, approved, scratch feature

#124 Sprite list
  features/features.json
  features/list-sprites.js
Labels: feature, scratch feature

#125 Check if Trending
  features/check-if-trending.js
  features/features.json
Labels: feature, scratch feature
