Repository STForScratch/ScratchTools, pull requests merged in 2022-09, with the labels that each got.

#178 Preview textboxes
  features/features.json
  features/preview-textboxes.js
Labels: feature, approved, priority #2, scratch website

#179 Hide studio activity notifications
  features/features.json
  features/hide-studio-messages.js
Labels: feature, approved, priority #2, scratch website

#180 Update tags for old features
  features/features.json
Labels: priority #3

#181 Update compact navbar
  features/compact-navbar.js
Labels: enhancement, feature, approved, priority #2, scratch website

#182 Default to logo and infinite backpack scrolling
  features/default-to-local.js
  features/features.json
  features/infinite-backpack-scrolling.js
Labels: feature, approved, priority #2, scratch website

#183 Fix default to local not working with other languages
  features/default-to-local.js
Labels: feature, approved, priority #2, scratch website, bug fix

#185 Update version
  extras/new.js
  features/features.json
  manifest.json
Labels: approved, priority #2

#188 Add dynamic to features
  api/main.js
  extras/popup.js
  features/add-last-option-list.js
  features/advanced-search.js
  features/anti-generic.js
  features/april-fools.js
  features/aviate.js
  features/block-log.js
  features/block-messages.js
  features/box-shadows.js
  features/check-if-trending.js
  features/clone-counter.js
  features/custom-fonts.js
  features/features.json
Labels: enhancement, approved

#189 Move leopard button to dropdown menu and make dynamic
  features/features.json
  features/leopard.js
Labels: enhancement, approved, priority #3

#192 Add warning functionality and add to features
  extras/popup.js
  extras/stsettings.css
  features/features.json
Labels: enhancement, approved, priority #2, settings page

#196 Readme Update
  README.md
Labels: enhancement, approved
