Repository STForScratch/ScratchTools, pull requests merged in 2022-12, with the labels that each got.

#276 Update addToSpace API
  api/spaces.js
Labels: enhancement, priority #2

#274 Host images with assets.scratch.mit.edu on the forums
  features/features.json
  features/upload-img-directly.js
Labels: feature, priority #3, scratch website

#278 Leave Studio Button
  features/features.json
  features/leave-studio.js
Labels: feature, priority #2, scratch website

#273 User Statistics + Frontpage Curator Link
  features/features.json
  features/frontpage-curator.js
  features/user-stats.js
Labels: bug, feature, priority #3, scratch website

#280 Move button + minimized project credits
  features/features.json
  features/minimized-remix-credits.js
Labels: feature, priority #2, scratch website

#282 Update anti-generic.js
  features/anti-generic.js
Labels: enhancement, priority #3, scratch website

#292 start/stop hotkeys
  features/features.json
  features/start-stop-hotkeys.js
Labels: feature, priority #2, scratch website

#293 exact join date
  features/exact-join-date.js
  features/features.json
Labels: feature, priority #2, scratch website

#294 User hover cards
  features/features.json
  features/hover-user-cards.js
Labels: feature, priority #2, scratch website

#295 Add styles API
  api/main.js
Labels: priority #2

#296 remove useless console log
  features/sprite-clones.js
Labels: enhancement, priority #3, scratch website

#297 Search Context Menus
  features/features.json
  features/search-context-menus.js
Labels: feature, priority #2, scratch website

#298 Fix Easter Egg features on settings page
  extras/popup.js
Labels: priority #1, settings page, popup, bug fix

#299 bump version
  extras/new.js
  manifest.json
Labels: priority #3
