Repository STForScratch/ScratchTools, pull requests merged in 2023-04, with the labels that each got.

#378 sidebar updates
  features/features.json
  features/sidebar.js
Labels: enhancement

#382 Better changelog
  .DS_Store
  changelog/background.svg
  changelog/changes.json
  changelog/index.html
  changelog/script.js
  changelog/style.css
  extras/background.js
Labels: enhancement, priority #2

#383 Fix sprite data
  features/sprite-data.js
Labels: priority #1, bug fix

#384 Fix collapse blocks
  features/collapse-blocks.js
Labels: priority #1, bug fix

#385 Fix <a> for credits
  extras/index.html
  extras/popup.js
Labels: priority #2, bug fix

#386 Better settings page
  extras/background.js
  extras/index.html
  extras/popup.html
  extras/popup.js
Labels: priority #1, popup/settings, bug fix

#381 Onboarding
  brand/SpaceGrotesk.ttf
  extras/background.js
  features/images/collapse-blocks.png
  features/images/get-project-tags.png
  features/images/search-context-menus.png
  onboarding/background.svg
  onboarding/index.html
  onboarding/script.js
  onboarding/style.css
Labels: priority #1, popup/settings

#387 Resources for feature v2 and original buttons
  api/main.js
  changelog/changes.json
  extras/background.js
  features/features.json
  features/original-buttons/data.json
  features/original-buttons/resources/fav-gray.svg
  features/original-buttons/resources/fav-yellow.svg
  features/original-buttons/resources/love-gray.svg
  features/original-buttons/resources/love-red.svg
  features/original-buttons/resources/remix-gray.svg
  features/original-buttons/resources/views-gray.svg
  features/original-buttons/script.js
  manifest.json
Labels: enhancement, priority #1, new feature

#388 Fix opacity on views and remixes buttons
  features/original-buttons/script.js
Labels: bug fix

#391 Generate features code
  extras/popup.js
Labels: priority #2, popup/settings

#395 Feature pages + fix width on popup titles
  extras/background.js
  extras/feature/banner.svg
  extras/feature/index.html
  extras/feature/script.js
  extras/feature/style.css
  extras/popup.html
  manifest.json
Labels: enhancement, priority #1, popup/settings, bug fix

#397 Creator badges
  features/creator-badge/data.json
  features/creator-badge/script.js
  features/creator-badge/style.css
  features/features.json
Labels: priority #2, new feature

#398 Remove old strings and fix nicknames
  _locales/en/messages.json
  _locales/es/messages.json
  features/nicknames.js
Labels: priority #1, bug fix

#400 Colored shadows
  features/colored-shadows/data.json
  features/colored-shadows/style.css
  features/features.json
Labels: priority #2, new feature

#405 Better clone counter
  features/clone-counter/data.json
  features/clone-counter/gobo.svg
  features/clone-counter/script.js
  features/clone-counter/style.css
  features/features.json
Labels: enhancement, bug fix

#407 Remove dynamic from clone counter
  features/clone-counter/data.json
Labels: bug fix

#408 Stats percentages
  features/features.json
  features/stats-percentages/data.json
  features/stats-percentages/script.js
Labels: priority #2, new feature

#409 Fix `stats-percentages`
  features/stats-percentages/script.js
Labels: priority #1, bug fix

#410 Improve unlisted projects
  api/main.js
  api/modal.css
  extras/background.js
  features/features.json
  features/unlisted-projects.js
  features/unlisted-projects/data.json
  features/unlisted-projects/script.js
  features/unlisted-projects/star-full.svg
  features/unlisted-projects/star.svg
  features/unlisted-projects/style.css
  manifest.json
Labels: enhancement, priority #1

#411 Fix some bugs with clone counter and popup
  extras/popup.js
  features/clone-counter/script.js
Labels: priority #2, popup/settings, bug fix

#412 Fix clone counter
  features/clone-counter/script.js
Labels: priority #1, bug fix

#413 Fix bugs with project title input
  api/main.js
  features/move-project-title-input.js
Labels: priority #1, bug fix

#416 no font-face
  changelog/style.css
  extras/feature/style.css
  onboarding/style.css
Labels: priority #2, bug fix

#419 Remove opacity slider
  features/features.json
Labels: priority #1, bug fix

#418 Change Onboarding Colours
  onboarding/background.svg
  onboarding/style.css
Labels: enhancement

#423 Fix nicknames JSON.parse
  features/nicknames.js
Labels: bug fix

#425 Better API system
  api/feature.js
  api/main.js
  api/modals.js
  extras/background.js
Labels: enhancement, priority #2

#428 Bump version to v2.27.0
  changelog/changes.json
  manifest.json
Labels: priority #2
