Repository STForScratch/ScratchTools, pull requests merged in 2023-01, with the labels that each got.

#306 Capitalize TurboWarp
  features/features.json
  features/turbowarp-button-in-editor.js
  features/turbowarp-button.js
Labels: priority #3, bug fix

#327 Update alarm
  extras/background.js
Labels: priority #1, bug fix

#340 Better method for Unbold Site Text + make dynamic
  features/features.json
  features/unbold-site-text.js
Labels: priority #1, bug fix

#341 Fix bugs with `remove-editor-icons` and `plain-background`
  api/main.js
  features/features.json
  features/plain-background.js
  features/remove-editor-icons.js
Labels: enhancement, bug fix

#342 Better method for review sprite watermark and make dynamic
  features/features.json
  features/sprite-watermark.js
Labels: enhancement, bug fix

#343 fix scrollable list items
  features/features.json
  features/scrollable-list-items.js
Labels: enhancement, bug fix

#345 Scroll Project Titles
  features/features.json
  features/scroll-project-titles.js
Labels: feature, priority #2, scratch website

#344 Unlisted project links
  features/features.json
  features/unlisted-projects.js
Labels: priority #1

#347 Fix search context menus description
  features/features.json
Labels: popup/settings, bug fix

#348 Finally remove the useless pages folder
  pages/all.js
  pages/discuss.js
  pages/editor.js
  pages/home.js
  pages/join.js
  pages/profile.js
  pages/project.js
Labels: priority #3

#349 set up for translations
  _locales/en/messages.json
  _locales/es/messages.json
  extras/popup.js
  manifest.json
Labels: priority #1

#350 Better translations + spanish
  _locales/en/messages.json
  _locales/es/messages.json
  extras/popup.js
Labels: priority #1, popup/settings, translations

#351 add more spanish strings
  _locales/es/messages.json
Labels: priority #2, translations

#352 Make update box go to front
  extras/new.js
Labels: priority #1, bug fix

#353 Remove follower count from my stuff
  features/follower-count.js
Labels: priority #1, bug fix

#355 Add feature compatibility for i18n
  _locales/en/messages.json
  _locales/es/messages.json
  extras/background.js
  features/load-more-forum-posts.js
Labels: priority #1, translations

#356 Format files, rearrange features, update message, and bump version
  _locales/en/messages.json
  _locales/es/messages.json
  api/main.js
  api/spaces.js
  api/vm.js
  extras/background.js
  extras/new.js
  extras/popup.js
  features/features.json
  features/load-more-forum-posts.js
  features/plain-background.js
  features/project-timer.js
  features/remove-editor-icons.js
  features/scroll-project-titles.js
  features/scrollable-list-items.js
  features/sprite-watermark.js
  features/unlisted-projects.js
  features/upload-img-directly.js
  manifest.json
Labels: priority #2

#357 Add russian
  _locales/ru/messages.json
Labels: translations

#359 Polish
  _locales/pl/messages.json
Labels: priority #2, translations

#360 Automatically search
  extras/index.html
  extras/popup.html
  extras/popup.js
Labels: priority #1, popup/settings, bug fix

#361 Fix duplicating unlisted button
  features/unlisted-projects.js
Labels: priority #2, bug fix

#362 Stop Open in Ocular from ruining quotes
  features/ocular-link.js
Labels: priority #1, bug fix

#363 Horizontal features
  extras/index.html
Labels: priority #2, popup/settings, bug fix

#364 Add additional strings
  _locales/en/messages.json
  _locales/es/messages.json
  _locales/pl/messages.json
  _locales/ru/messages.json
  extras/popup.js
Labels: priority #3, translations

#369 Fix unlisted projects button not showing for other languages
  features/unlisted-projects.js
Labels: priority #1, bug fix
