Repository STForScratch/ScratchTools, pull requests merged in 2023-06, with the labels that each got.

#508 Better onboarding
  features/images/get-project-tags.png
  onboarding/featured.json
  onboarding/images/collapse-blocks.png
  onboarding/images/isonline.png
  onboarding/images/search-context-menus.png
  onboarding/script.js
Labels: enhancement, priority #2

#509 Live character count
  features/features.json
  features/live-character-counts/data.json
  features/live-character-counts/forums.js
  features/live-character-counts/projects.js
  features/live-character-counts/studios.js
  features/live-character-counts/style.css
Labels: priority #2, new feature

#511 Add ScratchTools button to new editor
  api/main.js
  api/spaces.js
  extras/background.js
  manifest.json
Labels: enhancement, priority #2, popup/settings

#507 Simplify Editor Tabs
  features/features.json
  features/simplify-editor-tabs/data.json
  features/simplify-editor-tabs/style.css
Labels: new feature

#512 Option validation
  extras/popup/popup.js
Labels: enhancement, priority #1, popup/settings

#513 Update `advanced-search` to v2
  features/advanced-search.js
  features/advanced-search/data.json
  features/advanced-search/script.js
  features/advanced-search/style.css
  features/features.json
Labels: enhancement, priority #3

#514 Update `project-links` to v2
  features/features.json
  features/project-links.js
  features/project-links/data.json
  features/project-links/script.js
Labels: enhancement, priority #2

#517 Update similar for a few features
  features/display-name/data.json
  features/emoji-status/data.json
  features/features.json
  features/hide-block-category-names/data.json
  features/isonline/data.json
  features/plain-background/data.json
  features/simplify-editor-tabs/data.json
  features/two-colors/data.json
  features/two-colors/style.css
Labels: enhancement, priority #2, popup/settings

#519 Add explanation for "For you" section
  extras/icons/sparkle.svg
  extras/index.html
  extras/modals.css
  extras/popup/popup.js
  extras/style.css
Labels: enhancement, priority #2, popup/settings

#520 Add storage and update block features
  api/main.js
  extras/background.js
  extras/blocked.js
  extras/index.html
  features/block-messages.js
  features/block-messages/data.json
  features/block-messages/messages.css
  features/block-messages/messages.js
  features/block-messages/profile.css
  features/block-messages/profile.js
  features/block-studios.js
  features/block-studios/data.json
  features/block-studios/messages.css
  features/block-studios/messages.js
  features/block-studios/studios.js
  features/features.json
Labels: enhancement, priority #2

#521 Prepare for new Scratch editor
  api/main.js
  api/vm.js
  features/creator-badge/style.css
  features/get-project-tags.js
Labels: enhancement, priority #1

#522 Update changelog for v2.30.0
  changelog/changes.json
  features/features.json
Labels: priority #1, popup/settings

#524 Add settings feature element fix to changelog
  changelog/changes.json
Labels: priority #2, popup/settings, bug fix

#523 Bump version
  manifest.json
Labels: priority #1

#530 Use white-space: pre; with popular project description
  features/most-popular-project.js
Labels: priority #2, bug fix

#536 Create traps API
  api/main.js
  api/vm.js
Labels: enhancement, priority #3

#537 Inject styles faster
  api/main.js
  extras/background.js
  extras/inject-styles.js
  manifest.json
Labels: priority #1, bug fix
