Repository STForScratch/ScratchTools, pull requests merged in 2023-12, with the labels that each got.

#753 Follow on projects
  features/features.json
  features/follow-on-projects/data.json
  features/follow-on-projects/follow.svg
  features/follow-on-projects/script.js
  features/follow-on-projects/style.css
Labels: priority #2, new feature

#760 Flag on Profile
  features/features.json
  features/flag-on-profile/flag.js
  features/profile-flag/data.json
  features/profile-flag/script.js
Labels: priority #2, new feature

#749 Full Feature Settings Page - Scrolling Bug
  extras/index.html
  extras/style.css
Labels: priority #3, bug fix

#762 Fix display names, emoji statuses, feedback and support
  extras/background.js
  extras/dashboard/emojis.json
  extras/dashboard/index.html
  extras/dashboard/script.js
  extras/dashboard/style.css
  extras/page.js
  extras/popup/popup.html
  extras/popup/popup.js
  extras/support/support.js
  features/display-name/profile.js
  features/emoji-status/script.js
Labels: priority #1, popup/settings, bug fix

#763 Minor feature improvements
  features/follow-on-projects/script.js
  features/special-editor-fonts.js
Labels: enhancement, priority #3, bug fix
