Repository STForScratch/ScratchTools, pull requests merged in 2023-05, with the labels that each got.

#434 Better changelog
  changelog/dev.svg
  changelog/index.html
  changelog/script.js
  changelog/style.css
Labels: priority #2

#435 Better styling on changelog page
  changelog/index.html
  changelog/style.css
Labels: priority #3, bug fix

#436 Better settings page design
  extras/index.html
Labels: enhancement, priority #2, popup/settings

#437 Move search bar and add better navigation bar
  api/modal.css
  changelog/style.css
  extras/blocked.js
  extras/feature/style.css
  extras/index.html
  extras/lightmode.css
  extras/modals.css
  extras/popup/popup.css
  extras/popup/popup.js
  extras/stsettings.css
  extras/stsettings.js
  onboarding/style.css
Labels: priority #1, popup/settings

#440 Fix original buttons not working
  features/original-buttons/style.css
Labels: priority #1, bug fix

#442 Fix clone counter bugs
  features/clone-counter/script.js
Labels: priority #2, bug fix

#445 Use page regex for userscripts/styles
  extras/background.js
  extras/popup/popup.js
  features/clone-counter/data.json
  features/colored-shadows/data.json
  features/creator-badge/data.json
  features/original-buttons/data.json
  features/stats-percentages/data.json
  features/unlisted-projects/data.json
  features/unlisted-projects/mystuff.css
  features/unlisted-projects/mystuff.js
  features/unlisted-projects/script.js
  features/unlisted-projects/style.css
Labels: enhancement, priority #2

#447 Fix options data not loading for Feature v2
  extras/background.js
Labels: priority #1, bug fix

#448 Add checkbox functionality and `settingChange` event
  api/feature.js
  api/main.js
  extras/index.html
  extras/popup/popup.css
  extras/popup/popup.js
Labels: enhancement, priority #1, popup/settings, bug fix

#450 Remove a credit from `hide-block-category-names` and update beta colors to blue
  extras/background.js
  extras/icons/beta/beta.svg
  extras/icons/beta/beta128.png
  extras/icons/beta/beta16.png
  extras/icons/beta/beta48.png
  extras/index.html
  extras/modals.css
  extras/popup/beta.css
  extras/popup/popup.js
  features/hide-block-category-names/data.json
Labels: enhancement, priority #1, popup/settings

#451 Better hide advertisements
  features/features.json
  features/hide-advertisements/data.json
  features/hide-advertisements/style.css
  features/hide-advertisements/three.js
  features/hide-advertisements/two.js
Labels: enhancement, priority #2

#452 Remove April Fools 2022
  features/april-fools.js
  features/features.json
Labels: priority #2, bug fix

#453 Set badge color blue for beta
  extras/background.js
Labels: enhancement, priority #3

#454 Bump to next version
  changelog/changes.json
  changelog/index.html
  manifest.json
Labels: priority #2

#456 Fix hide advertisements on 2.0 pages
  features/hide-advertisements/data.json
  features/hide-advertisements/three.js
  features/hide-advertisements/two.css
Labels: priority #1, bug fix

#457 Beta management + bump to beta
  changelog/beta.json
  extras/popup/popup.js
  manifest.json
Labels: priority #2

#459 More beta help
  changelog/beta.json
  extras/popup/popup.js
  onboarding/script.js
Labels: priority #2

#460 More beta help + bump beta version
  changelog/beta.json
  extras/popup/popup.js
  onboarding/script.js
Labels: priority #2

#466 Detect if a user is online
  extras/background.js
  extras/popup/popup.js
  features/features.json
  features/isonline/data.json
  features/isonline/script.js
  features/isonline/style.css
  features/message-count.js
Labels: priority #2, new feature

#467 Don't allow online detection to duplicate
  features/isonline/script.js
Labels: priority #1, bug fix

#468 Fix message count and add STE element modal
  api/modal.css
  api/modals.js
  features/isonline/script.js
  features/message-count.js
Labels: enhancement, priority #1, bug fix

#469 Better colored comments
  features/colored-comments.js
Labels: enhancement, priority #2

#470 Only show online if viewing a Scratch page
  extras/background.js
Labels: enhancement, priority #1

#471 Fix plain background
  features/features.json
  features/plain-background/data.json
  features/plain-background/style.css
Labels: priority #2, bug fix

#472 Fix icon not showing on settings page
  extras/index.html
Labels: priority #2, bug fix

#473 Remove beta check
  extras/popup/popup.js
Labels: priority #1

#476 Fix scrollbars
  extras/index.html
  features/scroll-project-titles.js
Labels: enhancement, priority #2, popup/settings, bug fix

#477 Change: Background Color For Ad Comments
  features/hide-advertisements/style.css
  features/hide-advertisements/two.css
Labels: enhancement, priority #3

#479 Display names
  api/verify.js
  extras/background.js
  features/display-name/data.json
  features/display-name/profile.css
  features/display-name/profile.js
  features/features.json
  features/isonline/data.json
Labels: priority #2, new feature

#480 Emoji statuses
  features/emoji-status/data.json
  features/emoji-status/script.js
  features/emoji-status/style.css
  features/features.json
Labels: priority #2, new feature

#481 Restyle username for display name feature
  features/display-name/profile.css
  features/display-name/profile.js
  features/features.json
Labels: enhancement, priority #3

#485 Feedback
  extras/feedback/index.html
  extras/feedback/script.js
  extras/feedback/style.css
  extras/popup/popup.js
Labels: priority #1, popup/settings

#486 Update isonline translations
  _locales/tr/messages.json
  api/feature.js
  features/colored-shadows/data.json
  features/isonline/data.json
  features/isonline/locales/de.json
  features/isonline/locales/en.json
  features/isonline/locales/es.json
  features/isonline/locales/fr.json
  features/isonline/locales/ru.json
  features/isonline/locales/tr.json
  features/isonline/script.js
Labels: priority #2, translations

#478 Border For Ad Comments
  features/hide-advertisements/style.css
Labels: enhancement, priority #3

#496 Remove translations
  _locales/en/messages.json
  _locales/es/messages.json
  _locales/ja/messages.json
  _locales/pl/messages.json
  _locales/ru/messages.json
  _locales/tr/messages.json
Labels: priority #1, bug fix, translations

#497 Update to next version
  changelog/changes.json
  extras/background.js
  extras/feedback/script.js
  extras/icons/feedback.svg
  extras/index.html
  extras/popup/popup.js
  extras/style.css
  extras/styles/light.css
  manifest.json
Labels: priority #2

#498 Add extension name translations
  _locales/en/messages.json
Labels: priority #1, translations

#499 dark mode for modals
  extras/modals.css
Labels: enhancement, popup/settings
