Repository STForScratch/ScratchTools, pull requests merged in 2023-09, with the labels that each got.

#686 Update Japanese translations
  extras/feature-locales/ja.json
Labels: priority #2

#687 Bump to stable
  changelog/changes.json
  manifest.json
Labels: priority #2

#689 Display commit on beta
  extras/icons/note.svg
  extras/popup/popup.js
Labels: priority #3, popup/settings

#690 Fix beta hash code
  extras/popup/popup.js
Labels: priority #1, popup/settings, bug fix

#691 Messages
  extras/index.html
  extras/messaging/script.js
  extras/messaging/style.css
  extras/style.css
  manifest.json
Labels: enhancement, priority #1, popup/settings

#692 Load more messages + go to comment
  extras/index.html
  extras/messaging/script.js
  extras/messaging/style.css
Labels: enhancement, priority #2, popup/settings

#694 Uninstall logging
  extras/background.js
Labels: enhancement, priority #2

#696 Remove project button in studios
  features/features.json
  features/remove-project-button/data.json
  features/remove-project-button/remove.svg
  features/remove-project-button/script.js
  features/remove-project-button/style.css
Labels: priority #2, new feature

#697 Save to watch later
  api/feature/traps.js
  features/features.json
  features/watch-later/data.json
  features/watch-later/mystuff.js
  features/watch-later/page/index.html
  features/watch-later/page/script.js
  features/watch-later/page/style.css
  features/watch-later/script.js
  features/watch-later/style.css
  features/watch-later/watch-later.svg
Labels: priority #2, new feature

#698 Update `hide-scratch-news` to v2
  extras/feature-locales/en.json
  features/features.json
  features/hide-scratch-news/data.json
  features/hide-scratch-news/style.css
Labels: enhancement, priority #2

#681 Port `admin-notifications` to V2
  features/admin-notifications.js
  features/admin-notifications/data.json
  features/admin-notifications/script.js
  features/admin-notifications/style.css
  features/features.json
Labels: enhancement, priority #2

#701 Live stats
  features/features.json
  features/live-stats/data.json
  features/live-stats/script.js
Labels: priority #2, new feature

#700 Wrap lists
  features/features.json
  features/wrap-lists/data.json
  features/wrap-lists/style.css
Labels: priority #2, new feature

#702 Improve localization
  api/feature.js
  extras/background.js
  feature-locales/isonline/en.json
  feature-locales/watch-later/en.json
  features/isonline/data.json
  features/isonline/locales/de.json
  features/isonline/locales/es.json
  features/isonline/locales/fr.json
  features/isonline/locales/ru.json
  features/isonline/locales/tr.json
  features/watch-later/mystuff.js
  features/watch-later/script.js
Labels: enhancement, priority #1

#704 Turkish
  _locales/tr/messages.json
  extras/feature-locales/tr.json
  feature-locales/isonline/tr.json
  feature-locales/watch-later/tr.json
Labels: enhancement, priority #2

#705 Japanese
  extras/feature-locales/ja.json
  feature-locales/isonline/en.json
  feature-locales/isonline/ja.json
  feature-locales/isonline/tr.json
  feature-locales/watch-later/en.json
  feature-locales/watch-later/ja.json
  feature-locales/watch-later/tr.json
Labels: priority #2

#706 Fix themes
  extras/popup/popup.js
Labels: priority #2, bug fix

#707 Bump to v3.3.0
  changelog/changes.json
  manifest.json
Labels: priority #3

#709 Create .gitignore
  .gitignore
Labels: enhancement, priority #2

#710 Fix localization
  feature-locales/echo-effect/en.json
  feature-locales/message-count/en.json
  feature-locales/statistics/en.json
  features/echo-effect/script.js
  features/message-count/data.json
  features/statistics/data.json
Labels: priority #1, bug fix
