Repository STForScratch/ScratchTools, pull requests merged in 2023-07, with the labels that each got.

#539 original-colors
  features/features.json
  features/original-colors/data.json
  features/original-colors/reply.svg
  features/original-colors/scratch-www.css
Labels: priority #1, new feature

#540 Update version
  changelog/changes.json
  features/original-colors/data.json
  manifest.json
Labels: enhancement, priority #2, bug fix

#541 Bump to v3.0.0
  manifest.json
Labels: priority #2

#545 Fix styles not being injected when service worker not running
  extras/background.js
Labels: priority #1, bug fix

#546 Fix scripts not running
  extras/background.js
Labels: priority #1, bug fix

#547 Fix forum coloring bug
  features/original-colors/scratch-www.css
Labels: priority #3, bug fix

#549 Beta program
  extras/background.js
  extras/beta/background.svg
  extras/beta/beta.json
  extras/beta/index.html
  extras/beta/style.css
  extras/popup/popup.js
Labels: enhancement, priority #2, popup/settings

#550 Fix styles not injecting after service worker restart
  extras/background.js
Labels: priority #1, bug fix

#558 Better waitForElements API
  .DS_Store
  api/main.js
Labels: enhancement, priority #2

#563 A few small settings page changes
  extras/icons/dark.svg
  extras/icons/light.svg
  extras/popup/popup.js
  extras/style.css
  extras/styles/dark.css
  extras/styles/light.css
Labels: enhancement, priority #3

#566 Add search filters
  extras/index.html
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
  extras/styles/dark.css
  extras/styles/light.css
  features/box-shadows/data.json
  features/clone-counter/data.json
  features/colored-shadows/data.json
  features/features.json
  features/original-colors/data.json
  features/plain-background/data.json
  features/unlisted-projects/data.json
Labels: enhancement, priority #1, popup/settings, bug fix

#568 Change colors + add divider
  extras/style.css
  extras/styles/dark.css
  extras/styles/light.css
Labels: enhancement, priority #2

#553 Make Text Color Match
  features/original-colors/scratch-www.css
Labels: priority #2, bug fix

#569 Support system
  extras/background.js
  extras/clicker.gif
  extras/icons/support.svg
  extras/index.html
  extras/leaderboard.html
  extras/lightmode.css
  extras/popup/popup.js
  extras/stsettings.js
  extras/style.css
  extras/styles/light.css
  extras/support/chat/index.html
  extras/support/chat/script.js
  extras/support/chat/style.css
  extras/support/index.html
  extras/support/page.js
  extras/support/style.css
  extras/support/support.js
Labels: enhancement, priority #1, popup/settings

#570 Fix issue with support chat
  extras/background.js
Labels: priority #1, bug fix

#571 Onboarding to html revamp
  extras/popup/popup.js
  extras/styles/purple.css
  onboarding/index.html
  onboarding/script.js
  onboarding/script2.js
  onboarding/style.css
  onboarding/themes/dark.svg
  onboarding/themes/light.svg
  onboarding/themes/purple.svg
Labels: enhancement, popup/settings

#548 hide-footer
  features/features.json
  features/hide-footer/data.json
  features/hide-footer/style.css
Labels: new feature

#572 Themes
  extras/background.js
  extras/feedback/index.html
  extras/feedback/style.css
  extras/icons/palette-fill.svg
  extras/index.html
  extras/popup/popup.js
  extras/style.css
  extras/styles/purple-light.css
  extras/styles/purple.css
  extras/styles/system.css
  extras/styles/theme.js
  extras/support/chat/index.html
  extras/support/chat/style.css
  extras/support/index.html
  extras/support/style.css
  onboarding/index.html
  onboarding/script.js
  onboarding/script2.js
  onboarding/style.css
  themes/settings/index.html
  themes/settings/script.js
  themes/settings/style.css
  themes/settings/svgData.svg
Labels: enhancement, priority #2, popup/settings

#575 Fix a few coloring bugs
  extras/index.html
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
Labels: priority #2, popup/settings, bug fix

#576 Change border radius
  extras/popup/popup.css
  extras/style.css
  extras/support/chat/style.css
  extras/support/style.css
  onboarding/style.css
Labels: priority #3, popup/settings

#577 Important messages
  features/block-messages/data.json
  features/features.json
  features/hide-advertisements/data.json
  features/important-messages/data.json
  features/important-messages/script.js
  features/important-messages/style.css
Labels: priority #2, new feature

#578 Fix important messages showing for unimportant messages
  features/important-messages/script.js
Labels: priority #2, bug fix

#579 New feedback center
  extras/background.js
  extras/feedback/index.html
  extras/feedback/page.js
  extras/feedback/script.js
  extras/feedback/style.css
  extras/popup/popup.js
  extras/style.css
Labels: enhancement, priority #2, popup/settings

#580 Fix duplicating clone counter on screen switch
  features/clone-counter/script.js
Labels: priority #2, bug fix

#581 Fix see-inside color
  features/original-colors/scratch-www.css
Labels: priority #2, bug fix

#582 Fix idea generator
  features/idea-generator.js
Labels: priority #1, bug fix

#583 Fix turbowarp button not working with tokens
  features/turbowarp-button-in-editor.js
Labels: priority #2, bug fix

#584 Fix creator badge purple for revert to blue
  features/original-colors/scratch-www.css
Labels: priority #3, bug fix

#585 Fix many feature titles/descriptions
  features/features.json
Labels: priority #2, bug fix

#586 Break text
  extras/feedback/style.css
Labels: priority #2, bug fix

#588 Shared clipboard
  features/features.json
  features/shared-clipboard/data.json
  features/shared-clipboard/script.js
Labels: priority #2, new feature

#589 Fix shared clipboard bug
  features/shared-clipboard/script.js
Labels: priority #1, bug fix

#590 Slash to search
  features/features.json
  features/slash-to-search/data.json
  features/slash-to-search/script.js
Labels: priority #3, new feature

#532 Simplify Action Buttons
  features/features.json
  features/simplify-action-buttons/data.json
  features/simplify-action-buttons/style.css
Labels: new feature

#591 Fix studio nav links
  features/original-colors/scratch-www.css
Labels: priority #2, bug fix

#593 Fix studio icons
  features/original-colors/scratch-www.css
Labels: priority #3, bug fix

#594 Fix a few bugs
  api/main.js
  extras/feedback/script.js
  extras/support/support.js
  features/sprite-clones.js
Labels: priority #2, bug fix

#595 Revert to blue improvements
  features/original-colors/scratch-www.css
Labels: enhancement, priority #2, bug fix

#596 Import/export settings
  extras/index.html
  extras/popup/popup.js
  extras/support/chat/script.js
Labels: enhancement, priority #1, popup/settings

#597 Fix download settings support chat bug
  extras/support/chat/index.html
Labels: priority #2, bug fix

#598 Autofocus search bar when settings opened
  extras/popup/popup.js
Labels: enhancement, priority #3, popup/settings

#600 Fix a few bugs
  features/comment-on-closed-profile.js
  features/original-colors/scratch-www.css
  features/user-bio.js
Labels: priority #1, bug fix

#601 Better more tutorials
  extras/popup/popup.js
  features/features.json
  features/more-tutorials/data.json
  features/more-tutorials/script.js
Labels: enhancement, priority #2, bug fix

#602 Changelog
  changelog/3/bg.svg
  changelog/3/images/better-blue.png
  changelog/3/images/chat.png
  changelog/3/images/feedback.png
  changelog/3/images/hide-footer.png
  changelog/3/images/important-messages.png
  changelog/3/images/peace.svg
  changelog/3/images/shared-clipboard.png
  changelog/3/images/simplify-action-buttons.png
  changelog/3/images/slash-to-search.png
  changelog/3/images/support.png
  changelog/3/images/themes.png
  changelog/3/index.html
  changelog/3/style.css
  changelog/changes.json
  extras/background.js
  extras/feedback/style.css
Labels: enhancement, priority #1

#603 News + fix auth
  extras/feedback/page.js
  extras/index.html
  extras/popup/popup.js
  extras/support/page.js
Labels: enhancement, priority #1, bug fix

#604 Update `preview-textboxes`
  features/features.json
  features/preview-textboxes.js
  features/preview-textboxes/data.json
  features/preview-textboxes/preview.svg
  features/preview-textboxes/profiles.js
  features/preview-textboxes/projects.css
  features/preview-textboxes/projects.js
  features/simplify-action-buttons/style.css
Labels: enhancement, priority #2, bug fix
