Repository STForScratch/ScratchTools, pull requests merged in 2023-08, with the labels that each got.

#607 Add palindromos to studio links credits
  features/studio-links/data.json
Labels: priority #3

#609 Fix forum colors
  features/original-colors/scratch-www.css
Labels: priority #2, bug fix

#610 Update spaces
  api/spaces.js
  features/clone-counter/script.js
  features/isonline/script.js
  features/live-character-counts/forums.js
  features/message-count.js
  features/move-project-title-input.js
  features/unlisted-projects/script.js
Labels: enhancement, priority #2

#611 Modules
  api/module.js
  extras/background.js
  features/isonline/data.json
  features/isonline/script.js
Labels: enhancement, priority #1

#612 Module improvements
  api/feature.js
  api/main.js
  api/module.js
  extras/background.js
  extras/popup/popup.js
Labels: enhancement, priority #1, bug fix

#613 isonline improvements
  features/isonline/data.json
  features/isonline/script.js
Labels: enhancement, priority #3

#614 Move share button
  features/features.json
  features/move-share-button/data.json
  features/move-share-button/script.js
Labels: priority #2, new feature

#616 Minor improvements + localization
  _locales/en/messages.json
  api/feature.js
  api/main.js
  api/module.js
  api/vm.js
  extras/background.js
  extras/feature-locales/en.json
  extras/index.html
  extras/popup/popup.html
  extras/popup/popup.js
  features/anti-generic.js
  manifest.json
Labels: enhancement, priority #1, bug fix

#617 Module improvements
  api/feature.js
  api/feature/index.js
  api/feature/self.js
  api/feature/traps.js
  api/module.js
  extras/background.js
  features/isonline/script.js
Labels: enhancement, priority #2

#618 Improve `message-count` and use modules everywhere
  api/module.js
  api/spaces.js
  extras/background.js
  extras/popup/popup.js
  features/features.json
  features/message-count/data.json
  features/message-count/locales/en.json
  features/message-count/script.js
Labels: enhancement, priority #2

#619 Echo effect
  api/feature/self.js
  api/main.js
  api/module.js
  extras/background.js
  features/echo-effect/data.json
  features/echo-effect/echo.svg
  features/echo-effect/script.js
  features/features.json
Labels: priority #2, new feature

#620 Hide on disable
  api/feature/self.js
  api/main.js
  api/module.js
  features/echo-effect/script.js
Labels: enhancement, priority #2

#621 Fix statistics
  features/features.json
  features/statistics/data.json
  features/statistics/locales/en.json
  features/statistics/script.js
Labels: priority #2, bug fix

#622 Add new tag
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
  features/features.json
Labels: enhancement, priority #2, popup/settings

#624 Fix `steal-game`
  features/features.json
  features/steal-game/script.js
Labels: priority #2, bug fix

#625 Fix search context menu coloring
  features/search-context-menus.js
Labels: priority #2, bug fix

#626 Load More Scratch News
  features/features.json
  features/more-news/data.json
  features/more-news/script.js
  features/more-news/style.css
Labels: priority #2, new feature

#629 Fix dumpster fire with custom studio section
  features/dumpster-fire/data.json
  features/dumpster-fire/script.js
  features/features.json
Labels: priority #2, bug fix

#630 Better search
  extras/popup/popup.js
Labels: enhancement, priority #2, popup/settings, bug fix

#633 Better search
  api/main.js
  extras/popup/popup.js
Labels: enhancement, priority #2

#526 Leave code blocks with their original fonts
  features/custom-fonts.js
Labels: priority #2, bug fix

#635 Fix beta program issues
  extras/background.js
Labels: priority #2, bug fix

#637 No Cache on Beta Program
  extras/background.js
Labels: priority #2, bug fix

#638 Update `ja` messages
  _locales/ja/messages.json
Labels: enhancement, priority #2

#639 Add japanese feature translations
  extras/feature-locales/ja.json
Labels: priority #2

#640 Fix updated version for `preview-textboxes`
  features/features.json
Labels: priority #2, bug fix

#641 Fix changelog
  changelog/changes.json
  changelog/script.js
Labels: priority #2, bug fix

#644 Fix sound editor `original-colors`
  features/original-colors/scratch-www.css
Labels: priority #2, bug fix

#645 New feature: `localized-explore`
  api/feature.js
  extras/popup/popup.js
  features/features.json
  features/hide-advertisements/three.js
  features/hide-advertisements/two.js
  features/hide-block-category-names/script.js
  features/localized-explore/data.json
  features/localized-explore/script.js
  features/localized-explore/style.css
Labels: priority #2, new feature

#646 Fix feature font size
  extras/popup/popup.css
  extras/style.css
Labels: priority #3, popup/settings, bug fix

#649 Fix translations breaking
  .vscode/settings.json
  extras/popup/popup.js
Labels: priority #1, popup/settings, bug fix

#656 Fix Unlisted Projects button not showing
  features/unlisted-projects/script.js
Labels: priority #2, bug fix

#661 Better logging
  api/main.js
Labels: enhancement, priority #2

#663 More studios
  features/features.json
  features/more-studios/data.json
  features/more-studios/script.js
  features/more-studios/style.css
Labels: priority #2, new feature

#664 Remove testing
  features/more-studios/script.js
Labels: priority #2, bug fix

#666 Opacity slider
  api/modal.css
  api/vm.js
  extras/icons/info.svg
  extras/icons/warning.svg
  extras/modals.css
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
  features/features.json
  features/opacity-slider/data.json
  features/opacity-slider/script.js
  features/opacity-slider/style.css
Labels: priority #2, new feature

#669 Update Green Flag Hotkeys
  features/features.json
  features/opacity-slider/script.js
  features/start-stop-hotkeys/data.json
  features/start-stop-hotkeys/script.js
Labels: enhancement, priority #2

#670 Add more info to `manifest.json`
  manifest.json
Labels: enhancement, priority #3

#671 Fix `default-to-local` for compatibility
  features/default-to-local/data.json
  features/default-to-local/script.js
  features/features.json
Labels: priority #3

#673 Trending features
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
Labels: enhancement, priority #3, popup/settings

#674 Prettier boolean options
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
Labels: enhancement, priority #2, popup/settings

#675 Love/favorite animations easter egg
  features/features.json
  features/love-fave-animate/data.json
  features/love-fave-animate/style.css
Labels: priority #3, new feature

#679 Update `right-side-flag` to v2
  features/features.json
  features/right-side-flag.js
  features/right-side-flag/data.json
  features/right-side-flag/style.css
Labels: enhancement, priority #2
