Repository STForScratch/ScratchTools, pull requests merged in 2023-10, with the labels that each got.

#712 Relevant Forum Posts
  api/main.js
  api/module.js
  extras/index.html
  extras/popup/popup.js
  features/features.json
  features/relevant-forum-posts/data.json
  features/relevant-forum-posts/script.js
  features/relevant-forum-posts/style.css
Labels: priority #2, popup/settings, bug fix, new feature

#718 Detect Blocklive
  api/blocklive-detection/blocklive-detect.js
  api/blocklive-detection/extensions.svg
  api/blocklive-detection/style.css
  api/main.js
  extras/background.js
  features/original-colors/scratch-www.css
Labels: enhancement, priority #3

#719 Change caching
  features/live-stats/script.js
  features/turbowarp-button-in-editor.js
  features/unlisted-projects/script.js
Labels: priority #1, bug fix

#720 Shorter unlisted links
  features/unlisted-projects/script.js
Labels: enhancement, priority #2

#721 Slower rotation for Blocklive modal
  api/blocklive-detection/blocklive-detect.js
Labels: enhancement, priority #3

#724 Full Size Trending Projects
  features/better-trending-thumbnails/data.json
  features/better-trending-thumbnails/style.css
  features/features.json
Labels: priority #3, new feature

#726 Better feature API
  api/blocklive-detection/blocklive-detect.js
  api/feature.js
  api/feature/auth.js
  api/feature/index.js
  api/feature/self.js
Labels: enhancement, priority #2

#727 Specific replies
  feature-locales/specific-replies/en.json
  features/features.json
  features/specific-replies/data.json
  features/specific-replies/script.js
Labels: priority #2, new feature

#728 Remove beta alerts
  extras/background.js
Labels: priority #2, bug fix

#729 Update `anti-generic` components
  features/anti-generic/data.json
Labels: enhancement, priority #3

#731 Temporarily remove blocklive detection
  extras/background.js
Labels: priority #2, bug fix

#732 Fix save button appearing in report modal
  features/watch-later/script.js
Labels: priority #2, bug fix

#733 Add cloud data warnings
  extras/feedback/page.js
  extras/popup/popup.css
  extras/popup/popup.html
  extras/support/page.js
  features/display-name/data.json
  features/display-name/profile.js
  features/emoji-status/data.json
  features/emoji-status/script.js
Labels: enhancement, priority #1, popup/settings

#735 Improve and fix `hide-project-tags`
  features/features.json
  features/hide-project-tags.js
  features/original-colors/scratch-www.css
Labels: enhancement, priority #2, bug fix

#737 Localization for v3.4.0
  extras/feature-locales/ja.json
  extras/feature-locales/tr.json
  feature-locales/echo-effect/ja.json
  feature-locales/echo-effect/tr.json
  feature-locales/message-count/ja.json
  feature-locales/message-count/tr.json
  feature-locales/specific-replies/en.json
  feature-locales/specific-replies/ja.json
  feature-locales/specific-replies/tr.json
  feature-locales/statistics/ja.json
  feature-locales/statistics/tr.json
Labels: priority #2

#738 Bump to v3.4.0
  changelog/changes.json
  manifest.json
Labels: priority #2

#740 Dark paint editor
  api/feature/traps.js
  api/spaces.js
  api/vm.js
  features/dark-paint-editor/dark.svg
  features/dark-paint-editor/data.json
  features/dark-paint-editor/script.js
  features/dark-paint-editor/style.css
  features/features.json
Labels: priority #2, new feature

#743 Add support for trending studios
  features/better-trending-thumbnails/style.css
Labels: enhancement

#744 Improve update to `fix-trending-thumbnails`
  features/better-trending-thumbnails/data.json
Labels: enhancement, priority #2, bug fix
