Repository STForScratch/ScratchTools, pull requests merged in 2024-06, with the labels that each got.

#821 Pin comments
  features/features.json
  features/pin-comments/data.json
  features/pin-comments/pin.svg
  features/pin-comments/script.js
  features/pin-comments/style.css
Labels: priority #2, new feature

#824 Summarized Descriptions
  features/features.json
  features/project-descriptions/data.json
  features/project-descriptions/script.js
  features/project-descriptions/star.svg
  features/project-descriptions/style.css
Labels: priority #2, new feature

#825 Add feature "project-miniplayer"
  features/features.json
  features/project-miniplayer/data.json
  features/project-miniplayer/script.js
  features/project-miniplayer/style.css
Labels: priority #2, new feature

#828 Total stats
  features/features.json
  features/total-stats/data.json
  features/total-stats/script.js
  features/total-stats/style.css
Labels: priority #2, new feature

#829 Fix search bar
  extras/popup/popup.css
Labels: priority #3, bug fix

#834 Bump to v3.8.0
  changelog/changes.json
  changelog/script.js
  features/features.json
  manifest.json
Labels: priority #2

#832 Select self
  features/features.json
  features/select-self/data.json
  features/select-self/script.js
Labels: priority #2, new feature

#837 Fix Positioning Issue
  features/project-descriptions/style.css
Labels: bug, priority #2

#839 Add manifest schema to `.vscode/settings.json`
  .vscode/settings.json
Labels: priority #3

#840 Snap scripts to grid
  features/features.json
  features/snap-to-grid/data.json
  features/snap-to-grid/script.js
Labels: priority #2, new feature

#841 Make necessary v3.9.0 changes
  features/features.json
  manifest.json
Labels: priority #2

#747 Consolidate Project Tags
  features/features.json
  features/hide-project-tags.js
  features/hide-project-tags/data.json
  features/hide-project-tags/script.js
Labels: priority #3, new feature

#823 [README] git install and pull fix
  README.md
Labels: priority #3

#848 View sprite layers
  features/features.json
  features/sprite-layers/data.json
  features/sprite-layers/script.js
  features/sprite-layers/style.css
Labels: priority: 3, new feature, status: needs review, scope: feature

#851 Fix `select-self` adding clones to dropdown
  features/select-self/script.js
Labels: type: bug, priority: 1, scope: feature

#852 Fix `project-descriptions` overlapping with Notes & Credits text
  features/project-descriptions/style.css
Labels: type: bug, priority: 2, scope: feature

#857 Better Cloud History
  features/better-cloud-history/data.json
  features/better-cloud-history/script.js
  features/better-cloud-history/style.css
  features/features.json
Labels: priority: 3, new feature, status: needs review, scope: feature

#861 Fix popup search bar
  extras/popup/popup.css
Labels: type: bug, priority: 2, scope: popup/settings

#862 Fix block count
  features/block-count-in-mystuff.js
Labels: type: bug, priority: 2, scope: feature

#863 Remove a few Scratch db features
  features/features.json
Labels: type: bug, priority: 2, scope: feature

#853 Add Feature "stage-in-spritepane"
  features/features.json
  features/stage-in-spritepane/data.json
  features/stage-in-spritepane/script.js
  features/stage-in-spritepane/style.css
Labels: priority: 3, new feature, status: needs review, scope: feature

#867 Fix `select-self` when reenabled
  features/select-self/script.js
Labels: type: bug, priority: 3, scope: feature

#869 Selection option
  extras/popup/popup.js
  extras/style.css
Labels: type: enhancement, priority: 3, scope: popup/settings, scope: feature api

#870 Minor dropdown fixes
  extras/popup/popup.css
  extras/style.css
Labels: type: bug, priority: 2, scope: popup/settings

#874 Add `feature.page` API
  api/feature/index.js
  features/profile-flag/script.js
Labels: type: enhancement, priority: 2, scope: feature api

#875 Update wording for clarity
  features/project-miniplayer/data.json
Labels: type: enhancement, scope: feature

#876 Update v3.9.0 translations
  extras/feature-locales/es.json
  extras/feature-locales/ja.json
  extras/feature-locales/tr.json
Labels: priority: 2, scope: localization

#873 Update profile flags
  features/features.json
  features/profile-flag/data.json
  features/profile-flag/script.js
  features/profile-flag/style.css
Labels: type: enhancement, scope: feature

#878 Bump to `v3.9.0`
  changelog/changes.json
  manifest.json
Labels: priority: 2, scope: manifest
