Repository STForScratch/ScratchTools, pull requests merged in 2024-01, with the labels that each got.

#764 Update translations
  extras/feature-locales/ja.json
  extras/feature-locales/tr.json
Labels: priority #2

#765 Bump to v3.5.0
  changelog/changes.json
  changelog/index.html
  changelog/style.css
  manifest.json
Labels: priority #2

#769 Remove old warnings
  features/display-name/data.json
  features/emoji-status/data.json
Labels: enhancement, priority #3

#770 Fix duplicating most popular project
  features/most-popular-project.js
Labels: priority #2, bug fix

#768 Fix Full-Size Trending Studios
  features/better-trending-thumbnails/data.json
Labels: priority #2, bug fix

#771 Awards
  changelog/index.html
  extras/awards/banner.svg
  extras/awards/index.html
  extras/awards/script.js
  extras/awards/style.css
  extras/index.html
Labels: enhancement, priority #2

#767 fix ste follow button when using compact buttons
  features/compact-buttons/project.css
  features/follow-on-projects/script.js
Labels: priority #2, bug fix

#774 Editor Comment Tags
  feature-locales/comment-tags/en.json
  features/comment-tags/colors.json
  features/comment-tags/data.json
  features/comment-tags/editor.css
  features/comment-tags/script.js
  features/features.json
Labels: priority #2, new feature

#775 Remove Jeffalo from credits
  features/features.json
Labels: priority #3

#777 More Key Inputs
  features/features.json
  features/more-key-inputs/data.json
  features/more-key-inputs/script.js
Labels: priority #2, new feature

#778 More block themes
  features/features.json
  features/more-block-themes/check.svg
  features/more-block-themes/circle.svg
  features/more-block-themes/colors.css
  features/more-block-themes/data.json
  features/more-block-themes/main.css
  features/more-block-themes/script.js
  features/more-block-themes/themes/dark.css
  features/more-block-themes/themes/transparent.css
  features/more-block-themes/themes/ultradark.css
Labels: priority #2, new feature

#779 Fix inputs
  features/more-block-themes/colors.css
Labels: priority #2, bug fix

#780 Make custom block colors compatible with dark modes
  features/editor-dark-mode.js
  features/more-block-themes/script.js
  features/more-block-themes/themes/transparent.css
Labels: enhancement, priority #3

#782 Localize `more-block-themes`
  feature-locales/more-block-themes/en.json
  features/more-block-themes/script.js
Labels: enhancement, priority #2
