Repository STForScratch/ScratchTools, pull requests merged in 2024-03, with the labels that each got.

#796 Blur modal
  features/blur-modal/data.json
  features/blur-modal/style.css
  features/features.json
Labels: priority #2, new feature

#797 Download project
  features/download-project/data.json
  features/download-project/download.svg
  features/download-project/script.js
  features/download-project/style.css
  features/features.json
Labels: priority #2, new feature

#798 Minor quick search bug fixes
  features/quick-search/script.js
Labels: priority #2, bug fix

#773 UPDATE: Improve code
  api/logging.js
  api/main.js
  api/modal.css
  extras/modals.css
  features/project-bar/style.css
Labels: priority #3

#800 Fix bug with show emoji name
  features/show-emoji-names/script.js
Labels: priority #2, bug fix

#801 Fix a few minor bugs
  api/april/index.js
  api/april/pong/script.js
Labels: bug fix

#803 Update localization
  _locales/es/messages.json
  extras/feature-locales/es.json
  extras/feature-locales/ja.json
  extras/feature-locales/tr.json
  feature-locales/comment-tags/es.json
  feature-locales/comment-tags/ja.json
  feature-locales/comment-tags/tr.json
  feature-locales/echo-effect/es.json
  feature-locales/isonline/es.json
  feature-locales/message-count/es.json
  feature-locales/more-block-themes/en.json
  feature-locales/more-block-themes/es.json
  feature-locales/more-block-themes/ja.json
  feature-locales/more-block-themes/tr.json
  feature-locales/specific-replies/es.json
  feature-locales/statistics/es.json
  feature-locales/watch-later/es.json
Labels: priority #2

#804 Update changelog + bump version
  changelog/changes.json
  manifest.json
Labels: priority #2
