Repository STForScratch/ScratchTools, pull requests merged in 2024-07, with the labels that each got.

#885 Fix options
  extras/popup/popup.js
Labels: type: bug, priority: 1, scope: popup/settings

#886 Bump to `v3.9.1`
  manifest.json
Labels: priority: 2, scope: manifest

#883 Fix `Plain-Background`
  features/plain-background/style.css
Labels: scope: feature, type: compatibility improvement

#884 Color Fixes
  features/original-colors/scratch-www.css
Labels: type: bug, priority: 3, scope: feature

#888 Fix Search Bar
  extras/popup/popup.css
Labels: type: bug, priority: 2, scope: popup/settings

#889 Custom explore redirect
  extras/popup/popup.css
  extras/style.css
  features/custom-explore/data.json
  features/custom-explore/script.js
  features/features.json
Labels: new feature, scope: feature

#892 Extend C Blocks
  features/chomp-blocks/data.json
  features/chomp-blocks/script.js
  features/features.json
Labels: new feature, scope: feature

#890 Project reactions
  api/feature/index.js
  api/feature/server.js
  features/features.json
  features/project-reactions/data.json
  features/project-reactions/emojis/beaming.svg
  features/project-reactions/emojis/crying.svg
  features/project-reactions/emojis/fire.svg
  features/project-reactions/emojis/hands.svg
  features/project-reactions/emojis/heart-eyes.svg
  features/project-reactions/emojis/heart-face.svg
  features/project-reactions/emojis/hearts.svg
  features/project-reactions/emojis/laughing.svg
  features/project-reactions/emojis/popper.svg
  features/project-reactions/emojis/thumbsup.svg
  features/project-reactions/script.js
  features/project-reactions/style.css
Labels: priority: 3, new feature, status: needs review, scope: feature

#893 Custom Monitor Opacity
  extras/popup/popup.css
  extras/popup/popup.js
  features/change-monitor-opacity/data.json
  features/change-monitor-opacity/script.js
  features/features.json
Labels: new feature, scope: feature

#894 Allow strings for option types
  extras/popup/popup.js
Labels: type: enhancement, priority: 3, scope: popup/settings, scope: feature api

#895 Rotate gradients
  features/features.json
  features/rotate-gradient/data.json
  features/rotate-gradient/script.js
  features/rotate-gradient/style.css
Labels: new feature, scope: feature

#896 Fix a few things with feature API
  features/default-to-local/script.js
  features/download-project/script.js
  features/pin-comments/script.js
  features/sprite-layers/script.js
Labels: type: bug, priority: 3, scope: feature

#897 Fix sometimes crashing paint editor
  api/vm.js
Labels: type: bug, priority: 1, scope: feature api

#898 New feature: `paint-align`
  feature-locales/paint-align/en.json
  features/features.json
  features/paint-align/align.svg
  features/paint-align/data.json
  features/paint-align/script.js
  features/paint-align/style.css
Labels: new feature, scope: feature

#899 Localize `rotate-gradient`
  feature-locales/rotate-gradient/en.json
  features/rotate-gradient/script.js
Labels: type: enhancement, scope: localization, scope: feature

#900 Fix description
  features/paint-align/data.json
Labels: type: bug, priority: 2, scope: feature

#901 Update `paint-align` classes
  features/paint-align/script.js
Labels: type: enhancement, priority: 3, scope: feature

#902 Fix issue with `rotate-gradient` controls
  features/rotate-gradient/script.js
Labels: type: bug, scope: feature

#903 Add shift selection
  features/paint-align/data.json
  features/paint-align/script.js
Labels: type: enhancement, priority: 3, scope: feature

#905 Fix `paint-align` not working with non-gradient fills
  features/paint-align/script.js
Labels: type: bug, priority: 2, scope: feature

#906 Thumbnail setter
  api/modals.js
  features/features.json
  features/upload-thumbnail/data.json
  features/upload-thumbnail/script.js
  features/upload-thumbnail/style.css
  features/upload-thumbnail/thumbnail-btn.svg
Labels: new feature, scope: feature

#910 New feature: `more-editor-fonts`
  api/modal.css
  api/modals.js
  features/features.json
  features/more-editor-fonts/data.json
  features/more-editor-fonts/script.js
  features/more-editor-fonts/style.css
  features/more-editor-fonts/text.svg
  features/special-editor-fonts.js
  libraries/opentype.js
  manifest.json
Labels: priority: 2, new feature, status: needs review, scope: feature

#912 Improve spacing for `more-editor-fonts` options
  features/more-editor-fonts/style.css
Labels: type: enhancement, scope: feature

#913 Fix settings booleans on popup/settings page
  extras/popup/popup.css
  extras/style.css
Labels: type: bug, scope: popup/settings

#908 Align to Center
  features/align-to-center/data.json
  features/align-to-center/icon.svg
  features/align-to-center/script.js
  features/align-to-center/style.css
  features/features.json
Labels: new feature, scope: feature

#914 Fix `select-self` leaving out important options
  features/select-self/script.js
Labels: type: bug, priority: 2, scope: feature

#915 Fix `align-to-center` not working when clicked
  features/align-to-center/script.js
Labels: type: bug, priority: 2, scope: feature

#917 Improve search system
  extras/index.html
  extras/popup/popup.js
Labels: type: enhancement, priority: 2, scope: popup/settings

#918 Fix feature "project-miniplayer"
  features/project-miniplayer/script.js
Labels: type: bug, priority: 3, scope: feature

#919 Very, very important feature
  extras/games/tetris/index.html
  extras/games/tetris/styles.css
  extras/games/tetris/tetris.js
  extras/popup/popup.js
Labels: type: enhancement, scope: popup/settings

#920 Better featured projects
  features/better-featured-projects/data.json
  features/better-featured-projects/script.js
  features/features.json
Labels: new feature, status: needs review, scope: feature

#924 Add feature "explore-filter"
  api/modal.css
  api/modals.js
  feature-locales/explore-filter/en.json
  features/explore-filter/data.json
  features/explore-filter/resources/calendar.svg
  features/explore-filter/resources/filter.svg
  features/explore-filter/resources/title.svg
  features/explore-filter/resources/user.svg
  features/explore-filter/script.js
  features/explore-filter/style.css
  features/features.json
Labels: new feature, scope: feature

#925 Fix `explore-filter` in studios
  features/explore-filter/style.css
Labels: type: bug, priority: 2, scope: feature

#926 Remove somewhat unnecessary console log
  features/align-to-center/script.js
Labels: type: bug, scope: feature

#928 Studio Creation Date
  features/features.json
  features/studio-creation-date/calendar.svg
  features/studio-creation-date/data.json
  features/studio-creation-date/script.js
Labels: new feature, scope: feature

#931 Remove Aviate Feature
  features/aviate.js
  features/features.json
Labels: type: bug, priority: 2, scope: feature

#935 Video recorder feature
  features/features.json
  features/video-recorder/data.json
  features/video-recorder/popup.html
  features/video-recorder/style.css
  features/video-recorder/video-recorder.js
Labels: new feature, scope: feature
