Repository STForScratch/ScratchTools, pull requests merged in 2025-02, with the labels that each got.

#994 Fix Turbowarp Editor Button
  features/turbowarp-button-in-editor.js
Labels: type: bug

#999 Added more title keywords for Anti-generic
  features/anti-generic/script.js
Labels: type: enhancement, scope: feature

#963 Fix feature `project-miniplayer`
  features/project-miniplayer/script.js
Labels: type: bug, scope: feature
