Repository STForScratch/ScratchTools, pull requests merged in 2025-08, with the labels that each got.

#1011 Compare languages
  features/localized-explore/data.json
  features/localized-explore/script.js
Labels: type: enhancement, priority: 2, status: needs review, scope: feature

#1014 Fix Follow on Project
  features/follow-on-projects/data.json
  features/follow-on-projects/script.js
Labels: type: bug, priority: 1, status: needs review, scope: feature

#1013 Fix STE Settings Icon in Editor
  api/main.js
Labels: priority: 2, scope: popup/settings, status: needs review, type: compatibility improvement

#1018 Class Names API
  .github/scripts/extract-classnames.js
  .github/workflows/extract-classnames.yml
  api/module.js
  class-names.json
Labels: scope: feature api

#1019 Update `advanced-search`
  .github/scripts/extract-classnames.js
  .github/workflows/extract-classnames.yml
  features/advanced-search/script.js
Labels: type: enhancement, scope: feature

#1024 New feature: `comment-newlines`
  features/comment-newlines/data.json
  features/comment-newlines/script.js
  features/comment-newlines/style.css
  features/features.json
Labels: new feature, scope: feature

#1026 Improve "New" and "Updated" tags
  extras/popup/popup.css
  extras/popup/popup.js
  extras/style.css
Labels: type: enhancement, scope: popup/settings
