Repository STForScratch/ScratchTools, pull requests merged in 2025-01, with the labels that each got.

#980 Use `Attribute Selectors` to fix Dark Mode
  features/editor-dark-mode.js
Labels: type: bug, type: enhancement, scope: feature

#979 Remove Delete Confirmation
  features/features.json
  features/remove-confirmation/data.json
  features/remove-confirmation/script.js
  features/remove-confirmation/style.css
Labels: new feature, status: needs review, scope: feature

#982 Style new banner link
  features/original-colors/scratch-www.css
Labels: type: enhancement

#985 Request permissions API
  api/feature.js
  api/main.js
  api/update/changelogs/forum.json
  api/update/changelogs/project.json
  api/update/changelogs/website.json
  api/update/icons/align.svg
  api/update/icons/change.svg
  api/update/icons/countdown.svg
  api/update/icons/date.svg
  api/update/icons/extend.svg
  api/update/icons/filesize.svg
  api/update/icons/filter.svg
  api/update/icons/font.svg
  api/update/icons/gift.svg
  api/update/icons/gradient.svg
  api/update/icons/logo.svg
  api/update/icons/nocloud.svg
  api/update/icons/opacity.svg
  api/update/icons/outline.svg
  api/update/icons/reaction.svg
  api/update/icons/record.svg
  api/update/icons/shapes.svg
  api/update/icons/thumbnail.svg
  api/update/icons/upload.svg
  api/update/icons/variable.svg
  api/update/index.js
  api/update/style.css
  build/index.js
  build/write-permissions.js
  extras/background.js
  manifest.json
Labels: type: enhancement, priority: 2, scope: feature api, scope: background

#986 Change to "Get live support"
  _locales/en/messages.json
  extras/index.html
Labels: type: enhancement, priority: 3, scope: popup/settings

#987 Bump to v4.0.0
  manifest.json
Labels: priority: 2
