Repository STForScratch/ScratchTools, pull requests merged in 2025-03, with the labels that each got.

#1000 Fix Featured Projects
  features/better-featured-projects/script.js
Labels: type: bug, scope: feature

#992 Fix Flag Feature
  features/profile-flag/script.js
Labels: scope: feature, type: compatibility improvement

#993 Fix for gdpr Accounts
  features/comment-on-closed-profile.js
Labels: type: bug, scope: feature

#995 Improve Favicon Messages
  features/favicon-messages/script.js
Labels: type: enhancement, scope: feature

#1001 Prepare for v4.1.0
  api/update/index.js
  extras/background.js
  features/features.json
  features/more-block-themes/script.js
  features/random-block-colors/check.svg
  features/random-block-colors/circle.svg
  features/random-block-colors/colors.css
  features/random-block-colors/data.json
  features/random-block-colors/script.js
  features/random-block-colors/style.css
  manifest.json
Labels: type: enhancement, priority: 2, scope: manifest, scope: feature, scope: background

#1004 Copy and Paste Lists
  api/feature.js
  features/copy-paste-lists/data.json
  features/copy-paste-lists/script.js
  features/features.json
Labels: priority: 2, new feature
